### ISSUE TITLE
`ConnectionInfoV2` and other fields are `null` for Intel XHCI 8086:1e31

### ISSUE THREAD

**Issue by dhinakg** [USBToolBox/tool#12]
I still have the same issue on 0.0.8

[noname.jpg](https://user-images.githubusercontent.com/83843623/117510854-613e0180-afbf-11eb-8483-f1bcdccc0373.jpg)

Debug file 
[debug.txt](https://github.com/USBToolBox/tool/files/6444423/debug.txt)

_Originally posted by @aguys123 in https://github.com/USBToolBox/tool/issues/9#issuecomment-834798228_

**Comment by dhinakg** [comment]
@aguys123 You have a very weird issue, can you please download [USBView.zip](https://github.com/USBToolBox/tool/files/6446843/usbview.zip) and do the following:

1. Download and open USBView
2. Find `Intel(R) USB 3.0 eXtensible Host Controller`
3. Click on a port that has nothing plugged in (a port on this controller)
4. Upload a screenshot of the window
5. Click on a port that has something plugged in (a port on this controller)
6. Upload a screenshot of the window

**Comment by aguys123** [comment]
There you go:

![intel usb 3 xhc](https://user-images.githubusercontent.com/83843623/117559113-3d5ce780-b0b5-11eb-9178-b8adc424d366.jpg)

![root hub](https://user-images.githubusercontent.com/83843623/117559122-48177c80-b0b5-11eb-8e35-131fe628c33c.jpg)

![no plug](https://user-images.githubusercontent.com/83843623/117559125-4ea5f400-b0b5-11eb-98d0-9bbba52660ce.jpg)

![plugged](https://user-images.githubusercontent.com/83843623/117559139-5f566a00-b0b5-11eb-8804-5d79bfab6e38.jpg)

![ejected](https://user-images.githubusercontent.com/83843623/117559141-65e4e180-b0b5-11eb-8847-e0d990ccf090.jpg)

[plugged info.txt](https://github.com/USBToolBox/tool/files/6446869/plugged.info.txt)

**Comment by dhinakg** [comment]
Wow, that's really weird, there's basically no information for your controller...

Just to make sure, this is Windows 10 right?

**Comment by aguys123** [comment]
Yep, Windows 10 October 2020. It's a laptop Acer V5-471G (i5-3317u, HM77, nvidia gt620m).

**Comment by aguys123** [comment]
@dhinakg I think it's a driver problem. Today I updated my USB driver, and it (v0.0.8) works.

**Comment by dhinakg** [comment]
Yea I'll add workarounds for if you don't update drivers but it looks like some stuff is just going to be missing if drivers aren't installed, so I'll add that to the README.

**Comment by aguys123** [comment]
Thank you for this great tool 👍

**Comment by dhinakg** [comment]
I've released 0.0.9 which hopefully fixes this. However, you've installed drivers so unless you want to uninstall them and test I'll close this.
