### ISSUE TITLE
Getting controllers... error: KeyError: 'DeviceId'

### ISSUE THREAD

**Issue by danut-betuel** [USBToolBox/tool#14]
Trying to use this tool on my PC:

Asus Z270E
i7 7700k
16gb Ram
Windows 10

and I get this:

![error](https://user-images.githubusercontent.com/22745724/117884301-21279900-b2b5-11eb-9763-85cb894ad6a9.png)

**Comment by dhinakg** [comment]
Hi, can you please upload a debug log from debug_dump.exe? It's available on the [releases tab](https://github.com/USBToolBox/tool/releases).

**Comment by danut-betuel** [comment]
After running debug_dumb.exe, I got this json file [https://gist.github.com/danut-betuel/8a2216cfa1831fa7ca55029fc4351615](url)

**Comment by dhinakg** [comment]
Can you please run `debug_dump.exe` from [here](https://github.com/USBToolBox/tool/suites/2720080689/artifacts/59938899)? I've made some changes.

**Comment by danut-betuel** [comment]
I got another json file https://gist.github.com/danut-betuel/a2bac33fda5523f8457ff4a65643cec7

**Comment by dhinakg** [comment]
I've released 0.0.9 which hopefully fixes this, please test.

**Comment by danut-betuel** [comment]
On 0.0.9 version I didn't get this error anymore.
