### ISSUE TITLE
error: KeyError: 'DeviceId'

### ISSUE THREAD

**Issue by shaelr** [USBToolBox/tool#15]
**Hardware:**
 - Motherboard Asus Prime X299 Deluxe
 - OS: Windows 10 x64

debug File
[debug.txt](https://github.com/USBToolBox/tool/files/6474557/debug.txt)

**Comment by shaelr** [comment]
Looks like its my bcm94360cd card not having drivers under windows... seems like others have this issue as well, maybe worth noting or to add a check to exclude that device when found.

**Comment by dhinakg** [comment]
Can you please run `debug_dump.exe` from [here](https://github.com/USBToolBox/tool/suites/2720080689/artifacts/59938899)? I've made some changes.

**Comment by tinybrain** [comment]
#18 will report 'Unknown' for empty properties for the device.

**Comment by dhinakg** [comment]
I've released 0.0.9 which hopefully fixes this, please test.
