### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by adrianlungu** [USBToolBox/tool#16]
**Describe the bug**
Ran `Windows.exe` and this is what it ran into while trying to do `Port Discovery`:

```
Getting controllers...
Traceback (most recent call last):
  File "Windows.py", line 149, in <module>
  File "Windows.py", line 32, in __init__
  File "base.py", line 50, in __init__
  File "base.py", line 680, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 222, in discover_ports
  File "Windows.py", line 111, in get_controllers
  File "Windows.py", line 35, in update_usbdump
  File "usbdump.py", line 214, in get_controllers
TypeError: 'NoneType' object is not subscriptable
[16964] Failed to execute script Windows
```

**Debugging information**
[debug_dump_01.zip](https://github.com/USBToolBox/tool/files/6481685/debug_dump_01.zip)

**Hardware:**
 - Gigabyte Z490 UD Rev 1.0
 - Windows 10

**Comment by dhinakg** [comment]
How many USB controllers do you have in your system? You can check in `Device Manager` > `Universal Serial Bus controllers`. Make sure you ignore the composite devices and root hubs and only look at host controllers.

**Comment by dhinakg** [comment]
I've released 0.0.9 which hopefully fixes this, please test.

**Comment by adrianlungu** [comment]
Seems to be working now! Thanks @dhinakg 

Gonna proceed further with setting up the usb ports and see how it goes.

**Comment by adrianlungu** [comment]
Ok, I've setup the kext, loaded it in OpenCore but it seems for some reason some USB ports which I've mapped are not recognized by Catalina. 🤔 

Should I open another issue for this and describe it in more details ?

**Comment by dhinakg** [comment]
Hmm - your borkiness is probably your mobo, tbh. Either that or you're missing drivers, as I saw a controller in your debug log but it was completely devoid of any information. There wasn't any info from WMI either, so I'm guessing it was either botched or you don't have drivers installed for it. This issue with companions could happen if some of the companions are on the botched controller.

**Comment by adrianlungu** [comment]
That makes sense. I'll close the issue since it has been resolved, thanks again!
