### ISSUE TITLE
Can't discovery on Windows 20H2

### ISSUE THREAD

**Issue by Matgen84** [USBToolBox/tool#17]
Hello,

Trying to use this tool on my PC Windows 20H2. USBTool 0.0.8

I select option D (discovery). Few second later, the tool closes itself. It crashes using cmd.

`Getting controllers...
Traceback (most recent call last):
  File "Windows.py", line 149, in <module>
  File "Windows.py", line 32, in __init__
  File "base.py", line 50, in __init__
  File "base.py", line 680, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 222, in discover_ports
  File "Windows.py", line 111, in get_controllers
  File "Windows.py", line 35, in update_usbdump
  File "usbdump.py", line 221, in get_controllers
  File "usbdump.py", line 185, in serialize_hub
  File "usbdump.py", line 185, in serialize_hub
  File "usbdump.py", line 182, in serialize_hub
KeyError: 'DeviceId'
[4604] Failed to execute script Windows`

Any solutions, please

**Comment by dhinakg** [comment]
Can you please run `debug_dump.exe` from [here](https://github.com/USBToolBox/tool/suites/2720080689/artifacts/59938899) and upload the resulting file?

**Comment by Matgen84** [comment]
Done. Debug file in attachment. Thanks

[Debug-USBTool.txt](https://github.com/USBToolBox/tool/files/6501641/Debug-USBTool.txt)

**Comment by Matgen84** [comment]
Hi
Windows Defender detect: Trojan:Win32/Sabsik.FL.A!ml
 Why ?
 Same issue : I select option D (discovery). Few second later, the tool closes itself. It crashes using cmd.

**Comment by dhinakg** [comment]
I've released 0.0.9 which hopefully fixes this, please test.

**Comment by Matgen84** [comment]
Thanks. 
Release 0.0.9: Discover Ports works and display the listing of USB ports. When I plug in a USB device into each port. I don't show my USB3 device.
[debug_009.txt](https://github.com/USBToolBox/tool/files/6506299/debug_009.txt)

My config: Gigabyte Aorus Master Z390, i7 9770K

**Comment by dhinakg** [comment]
Well, it's good that it's not crashing now at least.

In the debug log you sent, did you have anything else plugged in besides these?

![image](https://user-images.githubusercontent.com/17605561/118820240-16a46b00-b884-11eb-902a-b0962c02b35a.png)

If you have something that is not showing up, it's best to send a debug log with it plugged in.

**Comment by Matgen84** [comment]
Strangely, this morning, my USB3 key was not detected. But now it is working perfectly.
Thank you

**Comment by dhinakg** [comment]
To unselect ports, just type their number again, like you did to select them. If you're trying to disable ports detected as companions too, you can turn that off in settings.

Anyways, thank you for testing! I'm gonna close this issue now
