### ISSUE TITLE
UTBMap.kext not being loaded?

### ISSUE THREAD

**Issue by adrianlungu** [USBToolBox/tool#19]
I'm just leaving this here in case anyone else runs into this. 
Not sure if it's something on my end, or there was something preventing this from properly being loaded. 

I've been trying to load the generated `UTBMap.kext` for a couple of hours now and it didn't seem to work at all. Do note that I've generated the `kext` using Windows. Everything is up to date (including BIOS, drivers, etc.).

Kextutil was reporting the following:
```
Diagnostics for /Users/adrian/UTBMap.kext:
Warnings:
    Personality CFBundleIdentifier differs from containing kext's (not necessarily a mistake, but rarely done):
        XHC
    Personality CFBundleIdentifier names a kext that can't be found:
        'XHC' -> 'com.dhinakg.USBToolBox.kext'
    Kext has no executable or compatible version, so it should not declare any OSBundleLibraries.

Dependency Resolution Failures:
    No kexts found for these libraries:
        com.dhinakg.USBToolBox.kext
```

In the end, I stumbled upon this page: https://dortania.github.io/OpenCore-Post-Install/usb/manual/manual.html#special-notes

After following the guide there, I changed the following:
- Remove `OSBundleLibraries` (this may be the thing causing the dependency resolution failure ?)
- Use the `IOProviderClass` the guide recommended
- Change a few other things to be closer to the sample `plist` and the recommended manual mapping; kept the `IOProviderMergeProperties` intact.

In the end, this helped load the kext and have the XHC Ports correlate with the `IOProviderMergeProperties` specified in the `kext`, and System Report shows the proper USB ports now. 

I've attached the `before` (UTBMap.kext) and `after` (USBMap.kext) for reference. 

[usb kexts.zip](https://github.com/USBToolBox/tool/files/6525239/usb.kexts.zip)

**Comment by dhinakg** [comment]
Did you have `USBToolBox.kext` along with `UTBMap.kext`? See step 8 in the [README](https://github.com/USBToolBox/tool#usage).

**Comment by adrianlungu** [comment]
No, I did not;

I looked into the `USBToolBox.kext` repo and when I read
```
 However, it is not needed and must be removed if you choose to map from the start (ie. from Windows, using the USBToolBox tool).
```
I understood that I shouldn't have `USBToolBox.kext` alongside the `UTBMap.kext`.

**Comment by dhinakg** [comment]
I was referring to `UTBDefault.kext` with that sentence, although I see how that can be confusing. I'll fix it soon, but basically, `UTBDefault.kext` should be removed once you have a map

**Comment by adrianlungu** [comment]
No other USB or UTB related kext either; you can find a copy of exactly what I'm running here: https://github.com/adrianlungu/OpenCore-Z490-UD-rev-10

If I turn `USBMap.kext` off and turn `UTBMap.kext` on, OpenCore doesn't seem to run it. It does run `USBMap.kext` though which is `UTBMap.kext` with the changes I mentioned earlier.

**Comment by dhinakg** [comment]
Again:
`UTBMap.kext` requires `USBToolBox.kext`
`USBMap.kext` does not

The USBToolBox tool can generate both, but `UTBMap.kext` is default. You can switch to build maps that don't rely on `USBToolBox.kext` (option "Use Native Classes") in the tool's settings.

**Comment by adrianlungu** [comment]
Ah, ok, now it makes sense!

I wasn't sure what the `Use Native Classes` option would do. 

Might I propose a slight improvement in the docs for this repo ? Or if you're open to collabs I could give it a shot and cook up a PR ?

**Comment by dhinakg** [comment]
Up to you. Really need to work on proper docs (kext options, in depth how to map, etc) but I've just entered the period where I can't spend a lot of time.
