### ISSUE TITLE
Is SSDT-EC-USBX.aml / SSDT-USBX.aml need?

### ISSUE THREAD

**Issue by john-shine** [USBToolBox/tool#25]
After build kext map files, I wonder if also need put SSDT-EC-USBX.aml or SSDT-USBX.aml dsdt patch in ACPI folder when use opencore. I'm so confused

**Comment by TheHackGuy** [comment]
Yes you still need that.
These are ssdt not dsdt

Only use 1 of that ssdt's. Not both.

It is depending on your smbios if you need usbx. Which is mentioned in the dortania guide

**Comment by dhinakg** [comment]
Yes, USBToolBox does not inject power properties, only a port map. You still need the USBX SSDTs for power properties.

**Comment by john-shine** [comment]
Thx
