### ISSUE TITLE
Kernel Panic on Thinkpad T460P + macOS 11.4 && OC 0.70  

### ISSUE THREAD

**Issue by bitelmaniaco** [USBToolBox/tool#26]
![IMG_1320](https://user-images.githubusercontent.com/15702153/129475049-5826ee6e-e695-432a-b964-5dd06d95954f.jpeg)

I have the kext from Windows 10, and my config for the kexts are the next one:

![Captura de pantalla 2021-08-15 a las 12 18 52](https://user-images.githubusercontent.com/15702153/129475192-6355c247-6fd4-4e69-a98f-8d221888a484.png)

**Comment by dhinakg** [comment]
![image](https://user-images.githubusercontent.com/17605561/129489900-5ab11933-dd99-4290-80d8-b81573d5d4ee.png)

USBToolBox has a binary
