### ISSUE TITLE
usbtoolbox crashes

### ISSUE THREAD

**Issue by Finnasaurus** [USBToolBox/tool#27]
The .exe file would try to Discover controllers and crash. ( I also tried the .zip version and also with antivirus disabled)

**To Reproduce**
1. Go to Windows.exe and run it (result is the same when running it as admin)
2. Select "D"
3. Wait..

[debug.zip](https://github.com/USBToolBox/tool/files/7135247/debug.zip)
pastebin https://pastebin.com/GtNu8US3
_I can't seem to get it to upload .json, guess it doesn't support it?_

**Hardware:**
 - Gigabyte Aorus G1 Gaming X470
 - Windows 10 20H2
 - Usbtool 0.9

**Comment by dhinakg** [comment]
Please test with [0.1.0](https://github.com/USBToolBox/tool/releases/tag/0.1.0), it should fix your issue

**Comment by dhinakg** [comment]
Closing as no response, please create a new issue if this still persists
