### ISSUE TITLE
Cant Discover Ports in LTSB2016 Microsoft Windows [Version 10.0.14393]

### ISSUE THREAD

**Issue by roddy20** [USBToolBox/tool#30]
[dump.zip](https://github.com/USBToolBox/tool/files/7968742/dump.zip)
  #######################################################
 #                  Port Discovery                     #
#######################################################

Getting controllers... and nothing more
Worked OK with another Windows edition

**Comment by roddy20** [comment]
finally it works, but it took a very long time, maybe 5 minutes, i ll check later
It was much faster in newer Windows, is it Ok?

**Comment by dhinakg** [comment]
Sorry, I have been somewhat busy lately. I have been working on a Python rewrite of the backend (usbdump) but it will take a while to complete. I'm hoping this will let me debug issues with dumping info and will make things faster.

Regarding com.apple.driver.AppleUSBMergeNub, I can definitely add that for you. I will put it on the to-do list.

**Comment by roddy20** [comment]
OK, faster or slower, but it works!
Thanks, it will be great BTW the kext with com.apple.driver.AppleUSBMergeNub seems to be working in new macOS too, as "deprecated feature" so I dont need two different kexts

**Comment by dhinakg** [comment]
0.1.0 may fix the issue (I've fixed some stuff in usbdump, the backend). Please test with it, and if it doesn't work, send a new debug log from it (I added some code to log the duration for certain tasks, so I can hopefully pinpoint the issue).

I released 0.1.0 before I finished AppleUSBMergeNub so it'll probably be in 0.1.1

**Comment by roddy20** [comment]
Thanks, trying but some errors here
  #######################################################
 #                  Change Settings                    #
#######################################################

T.  Show Friendly Types: Enabled
    Show friendly types (ie. 'USB 3 Type A') instead of numbers.
N.  Use Native Classes: Enabled
    Use native Apple classes (AppleUSBHostMergeProperties) instead of the USBToolBox kext.
Traceback (most recent call last):
  File "Windows.py", line 152, in <module>
  File "Windows.py", line 35, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 675, in change_settings
  File "utils.py", line 202, in start
  File "utils.py", line 163, in print_options
  File "base.py", line 648, in <lambda>
  File "base.py", line 652, in color_status
KeyError: 'use_legacy_native'
[6488] Failed to execute script 'Windows' due to unhandled exception!

C:\Users\Rodion S>

**Comment by roddy20** [comment]
#######################################################
 #            Select Ports and Build Kext              #
#######################################################

Расширяемый хост-контроллер Fresco Logic USB 3.0 — 1.0 (Майкрософт) | USB 3.0 (XHCI) | 2/8 ports
[ ]  1.  Port 1 | USB 2.0 | USB 3 Type A (guessed) | Companion to 5
[ ]  2.  Port 2 | USB 2.0 | USB 3 Type A (guessed) | Companion to 6
[#]  3.  Port 3 | USB 2.0 | USB 3 Type A (guessed) | Companion to 7
[ ]  4.  Port 4 | USB 2.0 | USB 3 Type A (guessed) | Companion to 8
[ ]  5.  Port 5 | USB 3.0 | USB 3 Type A (guessed) | Companion to 1
[ ]  6.  Port 6 | USB 3.0 | USB 3 Type A (guessed) | Companion to 2
[#]  7.  Port 7 | USB 3.0 | USB 3 Type A (guessed) | Companion to 3
          - VLI Product String - operating at USB 3.0
[ ]  8.  Port 8 | USB 3.0 | USB 3 Type A (guessed) | Companion to 4

Intel(R) ICH9 Family USB универсальный хост-контроллер  - 2936 | USB 1.1 (UHCI) | 1/2 ports
[#]  9.  Port 1 | USB 1.1 | Type A (guessed)
          - CSR8510 A10 - operating at USB 1.1
[ ]  10. Port 2 | USB 1.1 | Type A (guessed)

Intel(R) ICH9 Family USB2 расширенный хост-контроллер  - 293A | USB 2.0 (EHCI) | 2/6 ports
[ ]  11. Port 1 | USB 2.0 | Type A (guessed)
[#]  12. Port 2 | USB 2.0 | Type A (guessed)
          - Generic USB Hub - operating at USB 2.0
            - E-MU 0202 | USB - operating at USB 2.0
            - USB DISK 2.0 - operating at USB 2.0
[ ]  13. Port 3 | USB 2.0 | Type A (guessed)
[ ]  14. Port 4 | USB 2.0 | Type A (guessed)
[ ]  15. Port 5 | USB 2.0 | Type A (guessed)
[#]  16. Port 6 | USB 2.0 | Type A (guessed)
          - Keyboard Hub - operating at USB 2.0
            - Apple Keyboard - operating at USB 1.1
            - USB Optical Mouse - operating at USB 1.1

Intel(R) ICH9 Family USB2 расширенный хост-контроллер  - 293C | USB 2.0 (EHCI) | 0/6 ports
[ ]  17. Port 1 | USB 2.0 | Type A (guessed)
[ ]  18. Port 2 | USB 2.0 | Type A (guessed)
[ ]  19. Port 3 | USB 2.0 | Type A (guessed)
[ ]  20. Port 4 | USB 2.0 | Type A (guessed)
[ ]  21. Port 5 | USB 2.0 | Type A (guessed)
[ ]  22. Port 6 | USB 2.0 | Type A (guessed)

Intel(R) ICH9 Family USB универсальный хост-контроллер  - 2937 | USB 1.1 (UHCI) | 0/2 ports
[ ]  23. Port 1 | USB 1.1 | Type A (guessed)
[ ]  24. Port 2 | USB 1.1 | Type A (guessed)

Intel(R) ICH9 Family USB универсальный хост-контроллер  - 2938 | USB 1.1 (UHCI) | 0/2 ports
[ ]  25. Port 1 | USB 1.1 | Type A (guessed)
[ ]  26. Port 2 | USB 1.1 | Type A (guessed)

Intel(R) ICH9 Family USB универсальный хост-контроллер  - 2934 | USB 1.1 (UHCI) | 0/2 ports
[ ]  27. Port 1 | USB 1.1 | Type A (guessed)
[ ]  28. Port 2 | USB 1.1 | Type A (guessed)

Intel(R) ICH9 Family USB универсальный хост-контроллер  - 2939 | USB 1.1 (UHCI) | 0/2 ports
[ ]  29. Port 1 | USB 1.1 | Type A (guessed)
[ ]  30. Port 2 | USB 1.1 | Type A (guessed)

Intel(R) ICH9 Family USB универсальный хост-контроллер  - 2935 | USB 1.1 (UHCI) | 0/2 ports
[ ]  31. Port 1 | USB 1.1 | Type A (guessed)
[ ]  32. Port 2 | USB 1.1 | Type A (guessed)

Binding companions is currently on.

Traceback (most recent call last):
  File "Windows.py", line 152, in <module>
  File "Windows.py", line 35, in __init__
  File "base.py", line 49, in __init__
  File "base.py", line 696, in monu
  File "utils.py", line 204, in start
  File "utils.py", line 188, in select
  File "base.py", line 337, in select_ports
KeyError: 'use_legacy_native'
[6596] Failed to execute script 'Windows' due to unhandled exception!

**Comment by dhinakg** [comment]
Can you delete the existing settings.json? I need to work on better settings handling in general, but for now that will work around it

**Comment by roddy20** [comment]
> Can you delete the existing settings.json? I need to work on better settings handling in general, but for now that will work around it

Yes! I deleted all the files from old release and now it works! Thanks a lot!

**Comment by dhinakg** [comment]
👍
