### ISSUE TITLE
About  create type

### ISSUE THREAD

**Issue by starlifezzz** [USBToolBox/tool#32]
HI . About  create type USBToolBox kext or native Apple kexts (AppleUSBHostMergeProperties)
What's the difference between them, which one is better? thankyou

**Comment by dhinakg** [comment]
Using native Apple kexts has the benefit of not needing any additional kext added while using the USBToolBox kext ensures that you don't have to rename your controller or deal with overriding the built-in Apple map. It's up to you which one you want to use, there are minimal differences. For simplicity, I recommend making one that relies on USBToolBox, but if you know what you are doing, you can go with the native kext approach.

**Comment by starlifezzz** [comment]
> Using native Apple kexts has the benefit of not needing any additional kext added while using the USBToolBox kext ensures that you don't have to rename your controller or deal with overriding the built-in Apple map. It's up to you which one you want to use, there are minimal differences. For simplicity, I recommend making one that relies on USBToolBox, but if you know what you are doing, you can go with the native kext approach.

Thank you
