### ISSUE TITLE
No native Apple kexts (AppleUSBHostMergeProperties) option?

### ISSUE THREAD

**Issue by Mushmuch** [USBToolBox/tool#40]
Hello,
The readme states:` If building a map that uses the USBToolBox kext, make sure to grab the [latest release](https://github.com/USBToolBox/kext/releases) of the kext too.`

However I can't see an option to build the kext using AppleUSBHostMergeProperties, not USBToolBox.
Is there a hidden option? Do I need to edit the .plist file manually?
I used the 0.1.1 in Windows 10
Best regards

**Comment by dhinakg** [comment]
Did you check settings?
![](https://i.dhinak.net/WindowsTerminal_2022-07-24_13-36-22.png)
