### ISSUE TITLE
Windows 10 getting ACPI BIOS ERROR 

### ISSUE THREAD

**Issue by dipaksarkar** [USBToolBox/tool#43]
After adding the generated UTBMap.kext and USBToolBox.kext  it's working fine for MacOS. But not working for Windows 10. It showing the error https://photos.app.goo.gl/SciReLVyiEwPMhvT8

**Comment by dhinakg** [comment]
USBToolBox only generates kexts, so there's no way it can affect your ACPI. You likely have an errant SSDT, please double check your ACPI

**Comment by dipaksarkar** [comment]
I have checked. It was perfectly working with AllUsbInject.kext getting this issue when i have added USBToolBox.

**Comment by dhinakg** [comment]
Ok, do the following:

* Disable all ACPI patches
* Disable all SSDTs
* Test booting windows

If it still fails, please upload your EFI.

**Comment by dipaksarkar** [comment]
It's working after disabling all ACPI > Add
![image](https://user-images.githubusercontent.com/33681276/187819721-76a65c49-6b34-4184-aa65-4199b1a343f7.png)

I'm not sure, will it effect anything?

**Comment by dhinakg** [comment]
Your ACPI is broken then, this is not a UTB issue. Go to forums for support

**Comment by dipaksarkar** [comment]
I have check OC documentation and it's needed.
![image](https://user-images.githubusercontent.com/33681276/187820140-3bbced74-68bf-48fa-9e85-f1356e156cef.png)
I have generated it with CorpNewt: [SSDTTime](https://github.com/corpnewt/SSDTTime)
Do you want me to upload the SSDTs?

**Comment by dipaksarkar** [comment]
> 

I have done some different test and found that it's actually happen when enabled SSDT-PLUG.aml
